### PornHUb
GET http://localhost:4000/phub/models/1

### PornHub Models Pages
GET http://localhost:4000/phub/models/1

### PornHub model Search
GET http://localhost:4000/phub/models-filter/la


### PornHub model videos
GET http://localhost:4000/phub/model-videos


### PornHub Heavy Data
GET http://localhost:4000/phub/loop-data


### PorHub url data
GET http://localhost:4000/phub/url


### RED TUBE
GET https://api.redtube.com/?data=redtube.Videos.searchVideos&output=json&search=angela+white&ordering=newest&thumbsize=big


### LOCAL REDTUBE MODEL VIDEOS
GET http://localhost:4000/rtube/model/sweetie-fox

### Model Info detailed PORNHUB
GET http://localhost:4000/phub/model-info/sweetie-fox


### Some test on PHUB API
GET http://localhost:4000/phub/test/All

### Another test on PHUB API
GET http://localhost:4000/phub/test2

### PornHub Pics Page
GET http://localhost:4000/phub/pics/3/Amateur

### Get album from scraping (test)
GET http://localhost:4000/phub/test3

### Model Search FILTER
GET https://scraping-server.vercel.app/phub/models-filter/sweetie

### GET ALL DATA (MODELS) FROM MONGODB 
GET http://localhost:4000/phmongo/data/3

### Search with MONGODB (local)
GET http://localhost:4000/phmongo/search-models/Fun

### Adding Data (Models Page)
GET http://localhost:4000/phmongo/models

### Adding Data (Models Info) HARD LOOP!!!!
GET http://localhost:4000/phmongo/models-info

### Search with MONGODB data (prod)
GET https://scraping-server.vercel.app/phmongo/search-models/sw

### Get All data from DB (prod)
GET https://scraping-server.vercel.app/phmongo/data/2

### Get model Info MONGODB
GET http://localhost:4000/phmongo/model/Cory%20Chase