### PornHUb
GET http://localhost:3000/phub/models/1


### PornHub model filter
GET http://localhost:3000/phub/models-filter/la


### PornHub model videos
GET http://localhost:3000/phub/model-videos


### PornHub Heavy Data
GET http://localhost:3000/phub/loop-data


### PorHub url data
GET http://localhost:3000/phub/url


### RED TUBE
GET https://api.redtube.com/?data=redtube.Videos.searchVideos&output=json&search=angela+white&ordering=newest


### LOCAL REDTUBE
GET http://localhost:3000/rtube/model