### PornHUb
GET http://localhost:4000/phub/models/1


### PornHub model Search
GET http://localhost:4000/phub/models-filter/la


### PornHub model videos
GET http://localhost:4000/phub/model-videos


### PornHub Heavy Data
GET http://localhost:4000/phub/loop-data


### PorHub url data
GET http://localhost:4000/phub/url


### RED TUBE
GET https://api.redtube.com/?data=redtube.Videos.searchVideos&output=json&search=angela+white&ordering=newest&thumbsize=big


### LOCAL REDTUBE MODEL VIDEOS
GET http://localhost:4000/rtube/model/sweetie-fox

### Model Info detailed PORNHUB
GET http://localhost:4000/phub/model-info/sweetie-fox


### Some test on PHUB API
GET http://localhost:4000/phub/test/All

### Another test on PHUB API
GET http://localhost:4000/phub/test2

### PornHub Pics Page
GET http://localhost:4000/phub/pics/3/Amateur

### Get album from scraping (test)
GET http://localhost:4000/phub/test3

### Model Search FILTER
GET https://scraping-server.vercel.app/phub/models-filter/sweetie

### GET DATA FROM MONGODB REMOTE
GET http://localhost:4000/phmongo/data

### Testing on VERCEL from MONGODB
GET https://scraping-server.vercel.app/phmongo/data